### ISSUE TITLE
Add option g:wiki_foldlevel

### ISSUE THREAD

**Issue by BirgerNi** [lervag/wiki-ft.vim#10]
I like to open wiki files with a specific fold level. The following command does job:

```markdown
autocmd BufRead,BufNewFile *.md setlocal foldlevel=2
autocmd BufRead,BufNewFile *.Rmd setlocal foldlevel=2
```

An option like `g:wiki_foldlevel` would be convenient. What do you think?

**Comment by lervag** [comment]
I think it is equally good to apply this in your own custom ftplugin, i.e. create `~/.config/nvim/ftplugin/markdown.vim` and add the desired config. I do this myself, e.g.:

https://github.com/lervag/dotnvim/blob/main/ftplugin/wiki.vim
