### ISSUE TITLE
Fold yaml header

### ISSUE THREAD

**Issue by BirgerNi** [lervag/wiki-ft.vim#11]
I often use Rmarkdown files in my wiki which have a `yaml` header like this:

```yaml
---
title: Title of the document
---
```

Since the content in the `yaml` header is rarely edited it would be great to have the possibility to fold that by default. Maybe with options like `g:wiki_fold_yaml` and `g:wiki_yaml_foldlevel`. What do you think?

**Comment by lervag** [comment]
I don't use yaml headers in my wiki. I think it could be better to use a more dedicated Markdown filetype plugin, which would support the yaml header and where such an option either already exists or would make more sense.
