### ISSUE TITLE
Enhance math support

### ISSUE THREAD

**Issue by j1-lee** [lervag/wiki-ft.vim#2]
Hi, I am trying out wiki.vim and wiki-ft.vim today, and I like it!

I would like to ask for some enhancement regarding math in wiki; there are two issues, which are shown in the following example.

## Minimal example code
**minimal.vim**
```vim
call plug#begin()
Plug 'lervag/vimtex'
Plug 'lervag/wiki.vim'
Plug 'lervag/wiki-ft.vim'
call plug#end()

" The following line would show that $$...$$ region is well-supported by pandoc, even when one wants to export to an html file.
" let g:wiki_export = {'ext': 'html', 'args': '--mathjax --standalone'}
```

**minimal.tex**
~~~tex
This code
```tex
\begin{aligned}
e &= \lim_{n\to\infty} \left(1 + \frac{1}{n}\right)^n\\
  &= \sum_{n=0}^\infty \frac{1}{n!}.
\end{aligned}
```
will produce the following:
$$
\begin{aligned}
e &= \lim_{n\to\infty} \left(1 + \frac{1}{n}\right)^n\\
  &= \sum_{n=0}^\infty \frac{1}{n!}.
\end{aligned}
$$
~~~

## Observed behavior
![Screenshot at 2021-01-04 19-01-05](https://user-images.githubusercontent.com/47399860/103591832-3f245d80-4ebf-11eb-8813-89eae61ecb33.png)

1. The multi-line math region 
```
$$
...
$$
```
is not highlighted.

2. As we can see, when combined with lervag/vimtex, the fence part of the `tex` code block is concealed to `“`. (This does not happen when vimtex turned off.)

## Expected behavior

1. I hope the multi-line math region to nest `tex` syntax. As `$$...$$` math region is supported by pandoc markdown (as well as other markdown variants as well), I think this is not too a far-fetched enhancement; instead, it might be useful for writing wiki pages that involve some small math.
    (Note that one _needs_ to use `$$...$$`, not `pre` block, in order to show the processed equation in the exported pdf or html documents).
2. I hope the code block fences to be not subject to the syntax nested in the block.

Thank you!

**Comment by lervag** [comment]
1. Seems fair, I'll look at it.

2. Should be solved now. Note that the reason for the "glitch" is because the entire fenced region allows tex syntax, and you have `set conceallevel=2` and conceals activated. I don't know a general way to avoid the tex syntax to match also on the fences, but I've updated to ignore the conflicting `texLigature` group.

**Comment by lervag** [comment]
Can you test now?

**Comment by j1-lee** [comment]
This is great, thank you!

**Comment by lervag** [comment]
Glad you like it!
