### ISSUE TITLE
Breakindent does not work

### ISSUE THREAD

**Issue by cristobaltapia** [lervag/wiki-ft.vim#3]
I don't know why, but the `breakindent` option of vim has no effect when using this filetype plugin.

**Comment by lervag** [comment]
Perhaps because of `set nowrap` (done by wiki-ft.vim)? (I believe there may be one or more options set by `ftplugin/wiki.vim` (wiki-ft.vim, that is) that are probably opinionated and should not be set by the ftplugin itself.)

**Comment by lervag** [comment]
https://github.com/lervag/wiki-ft.vim/blob/03a6e366065af6c507589466dc3a5ac1401cce6d/ftplugin/wiki.vim#L11-L25

**Comment by cristobaltapia** [comment]
Thanks! Setting the `wrap` options makes `breakindent` work again.

**Comment by lervag** [comment]
Great :)
