### ISSUE TITLE
treesitter support

### ISSUE THREAD

**Issue by pbutler** [lervag/wiki-ft.vim#4]
I honestly don't know enough about the underpinnings of treesitter and wiki-ft  and what would be required to make it work so this might be sill.  However, It would be great if there could be support enabled such that treesitter recognizes the code and latex blocks and highlights them accordingly.

**Comment by lervag** [comment]
I don't really know much about treesitter, or at least, not on how to use it or develop for it/with it. I do know of it and have at least partially understood its potential, but I have not had the time to look into it more deeply. I don't think I will any time soon either; sorry.

But please note that wiki-ft.vim really is quite minimal, and it represents a relatively standard Markdown flavor. Thus, perhaps it would be better to look for a markdown implementation with treesitter; I would be surprised if that was not already available? Then one could ask how to add support e.g. for new syntax elements such as wiki style links `[[ .... ]]`.

**Comment by pbutler** [comment]
Thanks will definitely look into it.
